spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kerneljavadb  # ???? ??? ?????? ???? ??
    username: mcw          # ???? ??? ??? ???? ??
    password: 1231      # ???? ??? ????? ??
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
